### ISSUE TITLE
Upload limit reached 

### ISSUE THREAD

**Issue by BoyOfChu** [JHU-MedImage-Reg/LUMIR_L2R#1]
When I am preparing to submit the results of the LUMIR task and upload the results, a prompt appears saying "Upload limit reached" when it reaches 80%. Is there any solution to this issue?

**Comment by junyuchen245** [comment]
Hi,

Please review these two posts:

1. [Discussion on upload limits despite multiple submissions allowed per day
](https://grand-challenge.org/forums/forum/general-548/topic/upload-limit-reached-despite-having-multiple-submissions-allowed-per-day-851/?post=2341)
2. [Submission Q&A](https://rnr-exm.grand-challenge.org/submission-qa/)

Based on these, it appears you might be encountering the second issue listed. To resolve this, you have a couple of options: You can register as a verified user, or try submitting your data in 16-bit precision by using the numpy operation ` .astype(np.float16)`.

Junyu

**Comment by BoyOfChu** [comment]
Thank you for your information. I've initiated the account verification process, although it may take some time. Additionally, nii files do not inherently support float-16.

**Comment by junyuchen245** [comment]
I see. It looks like getting a verified account is the only option. Thank you for bringing this to my attention.

Junyu
