### ISSUE TITLE
Submission error: disp_3485_0000_3484_0000.nii.gz is missing

### ISSUE THREAD

**Issue by BoyOfChu** [JHU-MedImage-Reg/LUMIR_L2R#2]
Hello, there is some thing wrong when I submit my results. "evalutils.exceptions.ValidationError: The displacement field disp_3485_0000_3484_0000.nii.gz is missing. Please provide all required displacement fields." It appears there is a discrepancy between the naming convention for deformation field files and the instructions outlined in the documentation. How should we resolve this issue?

**Comment by junyuchen245** [comment]
Hi,

The evaluation scripts support both naming conventions: either disp_PatID1_0000_PatID0_0000.nii.gz or disp_PatID1_PatID0.nii.gz, as shown here:
https://github.com/JHU-MedImage-Reg/LUMIR_L2R/blob/66d07da92e579fd25b6a43c22045234688179b30/L2R_LUMIR_Eval/evaluation.py#L68-L69

Please ensure that your submission adheres to these formats. For guidance on how to name your files correctly, please see the example provided here:

https://github.com/JHU-MedImage-Reg/LUMIR_L2R/blob/66d07da92e579fd25b6a43c22045234688179b30/TransMorph/infer_TransMorphTVF.py#L61-L74 

Please be aware that only .nii.gz files are accepted; submitting .npz files will result in an error.

Junyu
