### ISSUE TITLE
Broken Link for Sanity Check Segmentation Labels

### ISSUE THREAD

**Issue by wei086** [JHU-MedImage-Reg/LUMIR_L2R#3]
I noticed that the link provided for the segmentation labels in the training dataset's sanity check section is broken. Specifically, the following text in the README mentions a "download" link which appears to be non-functional:

Sanity Check: Since LUMIR focuses on unsupervised image registration, segmentation labels and landmarks for both the training and validation datasets are kept private. However, we provide a small subset to enable participants to perform sanity checks before submitting their results to the Grand Challenge.
Segmentation labels for 5 images in the training dataset (download) (Note that these labels are provided solely for sanity-check purposes and should not be used for training. The segmentation used for the test images may differ from the ones provided here.)
Manual landmarks for 10 images in the training dataset (TBA)

Could you please update the link or provide an alternative way to access these segmentation labels? This would help participants ensure their submissions are correctly validated before submitting to the Grand Challenge.

Thank you!

**Comment by junyuchen245** [comment]
Hi,

The download link has been updated.

Thanks,
Junyu
